services:
  - type: web
    name: birthday-project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn birthday_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
