# Generated by Django 5.2.1 on 2025-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celebrant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "attendance",
                    models.CharField(
                        choices=[
                            ("yes", "Yes, I will attend"),
                            ("no", "No, I cannot attend"),
                            ("maybe", "Maybe, not sure yet"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of additional guests (not including yourself)",
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True, help_text="Any dietary restrictions or allergies"
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Any special requests or accommodations needed",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Birthday message for the celebrant"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="How do you know Mr. Jamiu?",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RSVP",
                "verbose_name_plural": "RSVPs",
                "ordering": ["-created_at"],
            },
        ),
    ]
